"""Wallet 模块：数据模型 + CRUD + 信用管理"""
from .models import Base, User, Wallet, Transaction, ApiKey, Agent, UsageLog
from .crud import (
    create_user,
    get_user_by_id,
    get_user_by_email,
    get_user_by_phone,
    update_user,
    lock_user,
    create_wallet,
    get_wallet_by_user_id,
    update_wallet_balance,
    create_transaction,
    get_transactions,
    create_api_key,
    get_api_keys,
    get_api_key_by_hash,
    deactivate_api_key,
    create_agent,
    get_agents,
    get_agent_by_did,
    update_agent,
    create_usage_log,
    get_usage_logs,
)
from .credit import CreditService

__all__ = [
    "Base",
    "User",
    "Wallet",
    "Transaction",
    "ApiKey",
    "Agent",
    "UsageLog",
    "CreditService",
    # CRUD
    "create_user",
    "get_user_by_id",
    "get_user_by_email",
    "get_user_by_phone",
    "update_user",
    "lock_user",
    "create_wallet",
    "get_wallet_by_user_id",
    "update_wallet_balance",
    "create_transaction",
    "get_transactions",
    "create_api_key",
    "get_api_keys",
    "get_api_key_by_hash",
    "deactivate_api_key",
    "create_agent",
    "get_agents",
    "get_agent_by_did",
    "update_agent",
    "create_usage_log",
    "get_usage_logs",
]
